# The URL the site will be built for
base_url = "https://aisnorway.github.io/aisnorway.org"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The default language; used in feeds.
default_language = "no"

compile_sass = true

title = "AI Safety Norge"
description = "Hjem til det norske fellesskapet for KI Sikkerhet"

[languages.en]

title = "AI Safety Norway"
description = "Home of the AI Safety Norway community"

build_search_index = false

[languages.en.translations]

navhome = "Home"
navabout = "About"
navcontact = "Contact"
navactivity = "Activity"
navblog = "Blog"

generalcontact = "For general questions, please contact us at aisafety(at)gmail.com"
boardmembers = "Board members"

titleLeader = "Chief Operations Manager"
titleSecLeader = "Chief Internal Operations Manager"
titleEcoLeader = "Director of Financial Management"
titleTechLeader = "Chief Technology Developer"
titlePolicyLeader = "Policy Advocacy Leader"
titleResearchLeader = "Director of AI Research"

[translations]

navhome = "Hjem"
navabout = "Om"
navcontact = "Kontakt"
navactivity = "Aktivitet"
navblog = "Blogg"

generalcontact = "For generelle henvendelser vennligst ta kontakt på aisafetynorway(at)gmail.com"
boardmembers = "Styret"

titleLeader = "Operativ leder"
titleSecLeader = "Forskningsdirektør"
titleEcoLeader = "Finansdirektør"
titleTechLeader = "Teknologidirektør"
titlePolicyLeader = "Direktør for KI-politikk"
titleResearchLeader = "Forskningsveileder"

[markdown]
render_section_content = true

[extra]

# User settings
username = "AI Safety Norge"
user_description = "Hjem til det norske fellesskapet for KI Sikkerhet"
user_title = ""
email = "aisafetynorway@gmail.com"
twitter_username = "#"
github_username = "https://github.com/aisnorway"

# Google-analytics
google_analytics.id = ""

contacts = [
    { name = "William Wale", image ="/img/contacts/leader.jpg", title = "titleLeader", links = [
        { name = "email", url = "mailto:wiwal2741@uib.no", label = "Email", icon = "fa fa-envelope"},
    ] },
    
    { name = "Marius Binner", image ="/img/contacts/secleader.png", title = "titleSecLeader", links = [
        {name="Email", url="mailto:marbinner@gmail.com", label="Email", icon="fa fa-envelope"},
    ] },
    
    { name = "Sigurd Bakken-Snekkevik", image ="/img/contacts/ecoleader.jpg", title = "titleEcoLeader", links = [
        { name = "Phone Number", url = "tel:+4741652855", label = "Phone Number", icon = "fa fa-phone"},
        { name = "Linkedin", url = "https://no.linkedin.com/in/sigurd-bakken-snekkevik-977b7821", label = "LinkedIn", icon = "fa fa-linkedin"},
    ] },
    
    { name = "Christian Kårbø Engelsen", image ="/img/contacts/tecleader.jpg", title = "titleTechLeader", links = [
        { name = "Email", url ="mailto:ckengelsen97@gmail.com", label = "Email", icon = "fa fa-envelope"},
        { name = "Phone Number", url = "tel:+4799587363", label = "Phone Number", icon = "fa fa-phone"},
        { name = "Linkedin", url = "www.linkedin.com/in/christian-kårbø-engelsen-7a07941aa", label = "LinkedIn", icon = "fa fa-linkedin"},
        { name = "Github", url = "https://github.com/Cengelsen", label = "Github", icon = "fa fa-github"},
    ] },
    
    { name = "Casper M. B. Olsvik", image ="/img/contacts/polleader.png", title = "titlePolicyLeader", links = [
        { name = "Email", url ="mailto:cas.olsvik@gmail.com", label = "Email", icon = "fa fa-envelope"},
        { name = "Linkedin", url = "https://www.linkedin.com/in/casperolsvik/", label = "LinkedIn", icon = "fa fa-linkedin"},
    ] },

    { name = "Joakim Hauger Sunde", image="/img/contacts/scileader.png", title = "titleResearchLeader", links = [
        { name = "Email", url ="mailto:joakimhauger97@gmail.com", label = "Email", icon = "fa fa-envelope"},
        { name = "Linkedin", url = "https://www.linkedin.com/in/joakim-sunde-825a5b148/", label = "LinkedIn", icon = "fa fa-linkedin"},
    ]}
]
